"""Add custom file fields and content_type to Project

Revision ID: 1e5a45c6b00a
Revises: 39580658e57a
Create Date: 2026-06-24 22:07:59.330768

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '1e5a45c6b00a'
down_revision = '39580658e57a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.add_column(sa.Column('content_type', sa.String(length=32), nullable=True))
        batch_op.add_column(sa.Column('template_name', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('custom_html_file', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('custom_css_file', sa.String(length=256), nullable=True))
        batch_op.add_column(sa.Column('custom_markdown_file', sa.String(length=256), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('projects', schema=None) as batch_op:
        batch_op.drop_column('custom_markdown_file')
        batch_op.drop_column('custom_css_file')
        batch_op.drop_column('custom_html_file')
        batch_op.drop_column('template_name')
        batch_op.drop_column('content_type')

    # ### end Alembic commands ###
