"""add ip_logs model

Revision ID: 39580658e57a
Revises: c7d0e4e3d146
Create Date: 2026-05-08 22:35:14.425652

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '39580658e57a'
down_revision = 'c7d0e4e3d146'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ip_logs',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('ip', sa.String(length=45), nullable=False),
    sa.Column('city', sa.String(length=128), nullable=True),
    sa.Column('region', sa.String(length=128), nullable=True),
    sa.Column('country', sa.String(length=128), nullable=True),
    sa.Column('org', sa.String(length=256), nullable=True),
    sa.Column('asn', sa.String(length=64), nullable=True),
    sa.Column('latitude', sa.Float(), nullable=True),
    sa.Column('longitude', sa.Float(), nullable=True),
    sa.Column('timezone', sa.String(length=128), nullable=True),
    sa.Column('user_agent', sa.Text(), nullable=True),
    sa.Column('full_data', sa.JSON(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ip_logs')
    # ### end Alembic commands ###
